title: Ziyang Gong
author: Ziyang Gong
email: meetziyang@gmail.com
description: Ph.D. Student in Statistics | SWUFE
baseurl: ""
url: "https://gongziyang.com"
github_username: ziyangg98

google_analytics: G-BGM4D1P40Q

mathjax:
  enabled: true

navigation:
  - title: Home
    url: /
  - title: Research
    url: /research/
  - title: Publications
    url: /publications/

theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
  style: apa
  locale: en
  source: ./_bibliography/
  bibliography: references.bib
  bibliography_template: bib
  sort_by: year
  order: descending

exclude:
  - Gemfile
  - Gemfile.lock
  - .ruby-version
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .github/
  - .git/
  - .editorconfig
  - .gitignore
  - .pre-commit-config.yaml
  - .markdownlint.json
  - README.md
  - LICENSE
